#!/usr/bin/env bash

if [[ "$1" = "composer" ]]
then
    docker run --rm -v $(pwd)/webapp:/app composer/composer:1.1-alpine ${@:2}
    exit
elif [[ "$1" = "up" ]]
then
    docker-compose up -d --build
    exit
elif [[ "$1" = "down" ]]
then
    docker-compose down --rmi local -v
    exit
elif [[ "$1" = "start" ]]
then
    docker-compose start ${@:2}
    exit
elif [[ "$1" = "stop" ]]
then
    docker-compose stop ${@:2}
    exit
elif [[ "$1" = "halt" ]]
then
    docker-compose stop ${@:2}
    exit
else
    docker-compose ${@:1}
    exit
fi
