#!/usr/bin/env bash

DOCKER_MACHINE_NAME="lara-docker-dm"

if [[ "$1" = "up" ]]
then
    docker-machine create --driver virtualbox --virtualbox-cpu-count 2 ${DOCKER_MACHINE_NAME}
    eval $(docker-machine env ${DOCKER_MACHINE_NAME})

    echo "${DOCKER_MACHINE_NAME} is running at ip: `docker-machine ip ${DOCKER_MACHINE_NAME}`"
    exit
fi

eval $(docker-machine env ${DOCKER_MACHINE_NAME})

if [[ "$1" = "halt" ]]
then
    docker-machine stop ${@:2} ${DOCKER_MACHINE_NAME}
    exit
elif [[ "$1" = "destroy" ]]
then
    docker-machine rm ${@:2} ${DOCKER_MACHINE_NAME}
    exit
elif [[ "$1" = "env" ]]
then
    eval $(docker-machine env ${@:2} ${DOCKER_MACHINE_NAME})
    exit
elif [[ "$1" = "ip" ]]
then
    docker-machine ip ${@:2} ${DOCKER_MACHINE_NAME}
    exit
else
    docker-compose ${@:1}
    exit
fi
