version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: ./env/app.Dockerfile
    depends_on:
      - db
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./webapp/storage/logs:/var/www/html/storage/logs
      - ./env/app/php/conf.d/xdebug.ini.dev:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./env/app/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    environment:
      DB_HOST: 'db'
  http:
    build:
      context: ./
      dockerfile: ./env/http.Dockerfile
    depends_on:
      - app
    network_mode: "host"
    ports:
      - 80:80
      - 443:443
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
