version: '2'
services:
  webapp:
    build:
      context: .
      dockerfile: webapp.Dockerfile
    depends_on:
      - db
    volumes:
      - ./webapp/storage/logs:/var/www/html/storage/logs
      - ./env/php/conf.d/xdebug.ini.dev:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      DB_HOST: 'db'
  http:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 32080:80
      - 443
  db:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
  composer:
    image: composer/composer:1.1-alpine
    volumes:
      - ./webapp:/app