version: '2'
services:
  webapp:
    build: ./webapp
    depends_on:
      - db
    volumes:
      - ./webapp:/var/www/html
    environment:
      DB_HOST: 'db'
  http:
    build: ./env/http
    depends_on:
      - webapp
    volumes_from:
      - webapp:ro
    ports:
      - 80
      - 443
  db:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'